- name: Copy the mikrotik Exporter systemd service file
  template:
    src: mikrotik_exporter.service.j2
    dest: /etc/systemd/system/mikrotik_exporter.service
    owner: "{{ mikrotik_exporter_user }}"
    group: "{{ mikrotik_exporter_group }}"
    mode: 0644
  notify:
    - restart mikrotik exporter

- name: Create mikrotik-exporter main configuration file
  template:
    src: mikrotik_exporter.yml.j2
    dest: /etc/mikrotik_exporter.yml
    owner: "{{ mikrotik_exporter_user }}"
    group: "{{ mikrotik_exporter_group }}"
    mode: 0640
  notify: restart mikrotik exporter
